server:
  port: 80
mybatis:
#  mapper-locations: classpath:/mapper/*.xml
  configuration:
    call-setters-on-nulls: true  #空值也封装到map
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: rolecostomer
  registry:
    address: zookeeper://127.0.0.1:2181
