server:
  port: 84
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: daiwenxiang
    hikari:
      maximum-pool-size: 200
      minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    call-setters-on-nulls: true  #空值也封装到map
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: roleprovider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:  #协议
    port: 20884
    name: dubbo
  scan:
    base-packages: com.example.roleprovider.service